### ISSUE TITLE
Conflict with another Cookbook

### ISSUE THREAD

**Issue by IAPOLINARIO** [dhoer/chef-windows_autologin#3]
There is a conflict with the function "windows_user" when you try to use "Windows_AutoLogin" and "Database" Cookbook in the same project. The "Database" cookbook already have a function called "windows_user". 

The stack trace is the following: 

> Error executing action `enable` on resource 'windows_autologin[enable autologin]'
> ==> windows_env:     ================================================================================
> ==> windows_env:     Chef::Exceptions::ValidationFailed
> ==> windows_env:     ----------------------------------
> ==> windows_env:     Option windows_user must be a kind of [TrueClass, FalseClass]!  You passed "user".
> ==> windows_env:     Cookbook Trace:
> ==> windows_env:     ---------------
> ==> windows_env:     C:/chef/cache/cookbooks/database/libraries/resource_sql_server_database_user.rb:37:in `windows_user'
> ==> windows_env:     C:/chef/cache/cookbooks/windows_autologin/providers/default.rb:24:in `block (2 levels) in class_from_file'
> ==> windows_env:     C:/chef/cache/cookbooks/windows_autologin/providers/default.rb:20:in `block in class_from_file'

Database cookbook link: https://supermarket.chef.io/cookbooks/database

**Comment by dhoer** [comment]
This could be easily fixed by changing the method names from window... to windows_autologin_...

**Comment by sterago** [comment]
@dhoer how long would it take to release a new version of this cookbook in case I worked on a PR to solve this issue?
